### ISSUE TITLE
näytä koneen suositus myös opiskelijaa tarkistellessa

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/disa-tool#230]
add check for times there are no machine review available

![image](https://user-images.githubusercontent.com/28741135/65580689-d55e9980-df82-11e9-934f-7b49cb8c638d.png)

**Comment by jokkehasa** [comment]
Minusta tämä on melko tärkeä ominaisuus, eli ei "low priority". Eikö prosenttiosuus muuten näy jo opettajalle?
