### ISSUE TITLE
sort out dev env

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/disa-tool#244]
So little time, so much confusion. What's the best way to work these fixes?

1) Staging does not use shibboleth login info, and possibly has other stuff missing too?
- Shouldn't staging be okay with updating to use Shibboleth? What's different?

2) Local will need fakeshibbo support.

Using any amount of very limited to set env up reduces chances of doing actual value fixes.

**Comment by Rochet2** [comment]
We can now develop locally and in staging.
