### ISSUE TITLE
Poista "Valitse kaikki"

### ISSUE THREAD

**Issue by Rochet2** [UniversityOfHelsinkiCS/disa-tool#251]
Opiskelijoiden arvosanoja tarkastellessa nappi “Valitse kaikki” on hämäävä. Voisiko koko valinnan jättää pois?

rimi: onko tarkoitus poistaa vain valitse kaikki? Vai myös  poista valinnat?
Vai onko itseasiassa tarkoitus poistaa koko valintamahdollisuus?

**Comment by jokkehasa** [comment]
Valintaa ei voi jättää pois. Hämäävyys tulee siitä, että opettaja ei tajua valita opiskelijoita, kun haluaa laskea kaikille arvosanat uudestaan. Sama koskee csv-tiedostoja (opettaja lataa helposti tyhjän csv-tiedoston). Pikakorjaus olisi tuottaa virheteksti "Valitse ensin opiskelijat", jos yrittäisi laskea palautteet tai luoda csv:n tyhjällä opiskelijalistalla.
