### ISSUE TITLE
Student should not be able to access or edit self-assessment forms

### ISSUE THREAD

**Issue by Mahtis** [UniversityOfHelsinkiCS/disa-tool#63]
If a student goes to a address such as http://localhost:8080/selfassesment/response/5, they can select a self assessment, edit its questions and successfully save it to the database. This is not desirable.

**Comment by laimikko1** [comment]
Also prevent the user from viewing edit/create pages.
Regarding this, also prevent the edit/create pages from crashing if the user refreshes them.
